version: '3.9'

services:
  baetyl-postgres:
    build:
      context: ./etc/postgres
    container_name: baetyl-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - baetyl

  baetyl-go:
    build:
      context: .
    container_name: baetyl-go
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - "80:80"
    volumes:
      - .:/app:rw,cached
    depends_on:
      - baetyl-postgres
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      baetyl:
        aliases:
          - local.baetyl.com

  baetyl-push:
    build:
      context: ./etc/mercure
    container_name: baetyl-push
    restart: unless-stopped
    environment:
      - SERVER_NAME=:80
      - VIRTUAL_HOST=push-local.baetyl.com
      - MERCURE_PUBLISHER_JWT_KEY=!ChangeMe!
      - MERCURE_SUBSCRIBER_JWT_KEY=!ChangeMe!
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    volumes:
      - type: volume
        source: caddy_data
        target: /data
      - type: volume
        source: caddy_config
        target: /config
    networks:
      baetyl:
        aliases:
          - push-local.baetyl.com

  baetyl-adminer:
    image: adminer:4-standalone
    container_name: baetyl-adminer
    restart: always
    ports:
      - "8888:8080"
    networks:
      - baetyl

networks:
  baetyl:
    name: baetyl

volumes:
  dbdata:
    driver: local
  caddy_data:
  caddy_config:
