apiVersion: v1
kind: Service
metadata:
  name: baetyl-load-balancer
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    name: baetyl-app